In [19]:
import matplotlib.pyplot as plt
from qiskit.visualization import plot_histogram

# Numpy statevector simulator


Numpy is the core library for scientific computing in Python. Some key highlights of numpy:
* Python library containing math functions
* Written in C so it runs really fast!
* Contains lots of helper functions allowing for shorter, more readable code
* Contains fantastic documentation. [Numpy documentation](https://numpy.org/doc/stable/).

While not required, the general consensus is to import the whole numpy library and set it as the name `np`:

In [1]:
import numpy as np

## Arrays

Numpy provides a high-performance multidimensional array object, and tools for working with these arrays.



In [2]:
example_list = [0,1,2,3,4]

numpy_list = np.array(example_list)

print(example_list)
print(numpy_list)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


# Vectors

Arrays, matrices, and vectors are one and the same - it all has to do with dimension and space

1 Dimension = Array
2 Dimension = Vector or Matrix

### Example 1

Dimension of A = (2,1):

$$
\begin{bmatrix}
12 \\
20
\end{bmatrix}
$$

A is therefore a column vector as the the Column dimensions = 1

### Example 2

Dimension of B = (2,2):

$$
\begin{bmatrix}
5 & 8 \\
12 & 2
\end{bmatrix}
$$

B is therefore a Matrix as the the Column  dimensions = 2, and the Row dimensions = 2


## Making Vectors in Numpy

```python
vector_name = np.array([[Value],
                        [Value]])
```

In [9]:
vector1 = np.array([[1],
                    [0],
                    [1]])
vector1

array([[1],
       [0],
       [1]])

## Making Matrices in Numpy

```python
matrix_name = np.array([[row],
                        [row]])
```

In [3]:
matrix1 = np.array([[1, 0, 1],
                    [0, 1, 0],
                    [1, 0, 1]])
matrix1

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

# Multiplying Matrices

In [12]:
# Let's take another look at our matrix1 and vector1 from above
print("matrix 1: ")
display(matrix1)
print("vector 1: ")
display(vector1)

matrix 1: 


array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

vector 1: 


array([[1],
       [0],
       [1]])

# Dot Product

In [13]:
np.dot(matrix1, vector1)

array([[2],
       [0],
       [2]])

---

# Cool, So let's do some Quantum Computing with that!
---

## Make the X Gate

## Make the Y Gate

## Make the Z Gate

## Make the H Gate

# Make the $\lvert 0 \rangle$ State

# Make a gate application function

In [14]:
def apply_gate(gate, state):
    # Todo
    return state

In [47]:
new_state = np.dot(H, base)

# Make a function that applies gates

# Make a function that plots Statevectors as Probability histograms

### © 2022 The Coding School

**All rights reserved**

*Use of this activity is for personal use only. Copying, reproducing, distributing, posting or sharing this activity in any manner with any third party are prohibited under the terms of this registration. All rights not specifically licensed under the registration are reserved.*